//power = { 1: "查看菜单", 2: "查看页面", 3: "新增", 4: "修改", 5: "删除", 6："查看详情" 7: "审核", 8: "上传"，9:"状态" }
//options = { MENU: "查看菜单", CONTENT: "查看页面", ADD: "新增", UPDATE: "修改", DELETE: "删除", DETAIL: "查看详情", CHECK: "审核", UPLOAD: "上传"， STATUS:"状态" }
export const MENU = 1
export const CONTENT = 2
export const ADD = 3
export const UPDATE = 4
export const DELETE = 5
export const DETAIL = 6
export const CHECK = 7
export const UPLOAD = 8
export const STATUS = 9
